"""empty message

Revision ID: 454f227ee33e
Revises: 94ac953cc84f
Create Date: 2024-05-08 22:21:21.415164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454f227ee33e'
down_revision = '94ac953cc84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('empresa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('ciudad', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('eslogan', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='empresa_pkey'),
    sa.UniqueConstraint('ciudad', name='empresa_ciudad_key'),
    sa.UniqueConstraint('eslogan', name='empresa_eslogan_key'),
    sa.UniqueConstraint('nombre', name='empresa_nombre_key')
    )
    op.drop_table('fav_planet')
    # ### end Alembic commands ###
